### ISSUE TITLE
Straighten filaments

### ISSUE THREAD

**Issue by tischi** [ekatrukha/BigTrace#4]
Have you considered adding a button [Straighten], which would render the intensities along the filament in a new coordinate system where the filament would run straight long the x axis?

**Comment by ekatrukha** [comment]
Hello @tischi 

Do you mean, like "Plot Profile" in ImageJ?
Yes, I plan to work on this and + some additional basic measurements (length, ends distributions, etc) in the near future.

**Comment by ekatrukha** [comment]
Hi @tischi ,

fixed in the lastest release 0.0.5.
So far only for a one pixel thickness, but more is coming.

**Comment by tischi** [comment]
Super cool! Thanks a lot!!
