### ISSUE TITLE
Selecting semi-auto tracing channels

### ISSUE THREAD

**Issue by oanegros** [ekatrukha/BigTrace#7]
Currently, all channels are used in semi-auto trace mode, it would be nice to have a selection of channel(s) to trace on (or use the scaled intensities of the visualization for the hessian transform?)

**Comment by ekatrukha** [comment]
Hello @oanegros,

what do you mean, "all channels"? Right now for semi-auto trace it uses only "Active" channel, selected in the window.

As for the second suggestion, I see what I can do.
This week I plan to finish big release of with new BVV visualizer first. It would add gamma correction and alpha blending. It would complicate scaled intensities story :-\

**Comment by ekatrukha** [comment]
These issues should be closed in the newest release 0.1.0, check it out.
